# Generated by Django 3.1.5 on 2021-02-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artifact',
            new_name='ArtifactModel',
        ),
    ]
